apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    io.kompose.service: stocktakingbackend
  name: stocktakingbackend
spec:
  replicas: 1
  template:
    metadata:
      labels:
        io.kompose.service: stocktakingbackend
    spec:
      containers:
      - env:
        - name: STOCK_DB_HOST
          value: stock-db
        - name: STOCK_DB_NAME
          value: stock
        - name: STOCK_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: stocktaking-secret
              key: STOCK_DB_PASSWORD
        - name: STOCK_DB_USERNAME
          value: stock
        - name: STOCK_DOMAIN
          valueFrom:
            configMapKeyRef:
              name: stocktaking-config
              key: STOCK_DOMAIN
        image: psshpak/stocktakingbackend
        imagePullPolicy: Always
        name: stocktakingbackend
        ports:
        - containerPort: 8081
        resources: {}
      restartPolicy: Always
