apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: stocktakingbackend
  name: stocktakingbackend
spec:
  ports:
  - name: "8081"
    port: 8081
    targetPort: 8081
  selector:
    io.kompose.service: stocktakingbackend
status:
  loadBalancer: {}
