# Envoy proxy translates GRPC to GRPC-Web,
#  this is preferred setup for grpc-web.

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    io.kompose.service: stocktakingapi
  name: stocktakingapi
spec:
  replicas: 1
  template:
    metadata:
      labels:
        io.kompose.service: stocktakingapi
    spec:
      containers:
      - name: stocktakingapi
        image: envoyproxy/envoy:v1.10.0
        command: [ "/usr/local/bin/envoy", "-c", "/etc/envoy/envoy.yaml" ]
        ports:
        - containerPort: 80
        volumeMounts:
          - name: envoy-configmap
            mountPath: /etc/envoy
      restartPolicy: Always
      volumes:
      - name: envoy-configmap
        configMap:
          name: envoy-configmap
