version: '2'

tasks:
  up:
    dir: docker
    cmds:
      - docker-compose up -d

  down:
    dir: docker
    cmds:
      - docker-compose down

  ps:
    dir: docker
    cmds:
      - docker-compose ps

  logs:
    dir: docker
    cmds:
      - docker-compose logs

  build-backend:
    cmds:
      - docker build --tag psshpak/stocktakingbackend -f stocktakingbackend/Dockerfile .

  build-docs:
    cmds:
      - bin/docker-run {{.IMAGE}} plantuml -v -tsvg docs/diagrams/containers.puml
    vars:
      IMAGE: wanix/plantuml

  push:
    cmds:
      - docker push {{.PROJECT}}/stocktakingbackend
    vars:
      PROJECT: psshpak
