version: '2'

tasks:
  up:
    dir: docker
    cmds:
      - docker-compose up -d

  down:
    dir: docker
    cmds:
      - docker-compose down

  ps:
    dir: docker
    cmds:
      - docker-compose ps

  logs:
    dir: docker
    cmds:
      - docker-compose logs

  build-frontend:
    dir: stocktakingweb
    cmds:
      - npm install
      - npm run build

  build-backend:
    dir: stocktakingbackend
    cmds:
      - make

  build-api:
    cmds:
      - apitests/bin/generate-api-client
      - stocktakingbackend/bin/generate-api-docs

  build:
    cmds:
      - task: build-frontend
      - task: build-backend
      - task: build-api

  docker-build-frontend:
    cmds:
      - docker build --tag psshpak/stocktakingweb -f stocktakingweb/Dockerfile .

  docker-build-backend:
    cmds:
      - docker build --tag psshpak/stocktakingbackend -f stocktakingbackend/Dockerfile .

  docker-build:
    cmds:
      - task: docker-build-frontend
      - task: docker-build-backend

  docker-push:
    cmds:
      - docker push psshpak/stocktakingweb
      - docker push psshpak/stocktakingbackend

  build-docs:
    cmds:
      - bin/docker-run {{.IMAGE}} plantuml -v -tsvg docs/diagrams/containers.puml
    vars:
      IMAGE: wanix/plantuml

  push:
    cmds:
      - docker push {{.PROJECT}}/stocktakingbackend
    vars:
      PROJECT: psshpak

  # Runs backend API tests, assumes that docker-compose containers are running now
  apitests:
    cmds:
      - apitests/bin/run-tests

  run-web:
    dir: stocktakingweb
    cmds:
      - npm run start
