version: '2'

tasks:
  up:
    dir: docker
    cmds:
      - docker-compose up -d

  down:
    dir: docker
    cmds:
      - docker-compose down

  ps:
    dir: docker
    cmds:
      - docker-compose ps

  logs:
    dir: docker
    cmds:
      - docker-compose logs

  build-backend:
    cmds:
      - docker build --tag psshpak/stocktakingbackend -f stocktakingbackend/Dockerfile .

  push:
    cmds:
      - docker push psshpak/stocktakingbackend
    vars:
      PROJECT: psshpak
