#!/usr/bin/env bash

set -e

PROTOC_GEN_TS_PATH="./node_modules/.bin/protoc-gen-ts"
OUT_DIR="./generated"

mkdir -p "$OUT_DIR"

# Generate GPRC and protobuf
grpc_tools_node_protoc \
    --js_out="import_style=commonjs,binary:${OUT_DIR}" \
    --grpc_out="${OUT_DIR}" \
    --plugin=protoc-gen-grpc=`which grpc_tools_node_protoc_plugin` \
    --proto_path=../stocktakingapi \
    api.proto

# Generate d.ts
protoc \
    --plugin=protoc-gen-ts=./node_modules/.bin/protoc-gen-ts \
    --ts_out="${OUT_DIR}" \
    --proto_path=../stocktakingapi \
    api.proto
