apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: stocktaking-cert
spec:
  secretName: stocktaking-cert
  dnsNames:
  - shambir.site
  acme:
    config:
    - http01:
        ingress: stocktaking-ingress
      domains:
      - shambir.site
  issuerRef:
    name: letsencrypt-cert-issuer
