apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

secretGenerator:
- name: stocktaking-secret
  env: secrets/decrypted/secret.env
  type: Opaque
configMapGenerator:
- name: stocktaking-config
  literals:
  - STOCK_DOMAIN=localhost

resources:
- namespace-stocktaking.yaml
bases:
- ../../base
namespace: stocktaking

patchesStrategicMerge:
- ingress/ingress.yaml
- ingress/ingress-api.yaml
