apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: stocktaking
bases:
- ../../base
resources:
- namespace-stocktaking.yaml
- ingress/ingress.yaml
- ingress/certificate.yaml
- ingress/letsencrypt-cert-issuer.yaml

patchesStrategicMerge:
- db/stock-db-deployment-volume.yaml

secretGenerator:
- name: stocktaking-secret
  env: secrets/decrypted/secret.env
  type: Opaque
configMapGenerator:
- name: stocktaking-config
  literals:
  - STOCK_DOMAIN=shambir.site
