version: "3"

services:
  stock-db:
    image: "postgres:11-alpine"
    container_name: "stock-db"
    volumes:
      - "postgres-data:/var/lib/postgresql/data"
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=stock
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=stock

  stocktakingbackend:
    image: "psshpak/stocktakingbackend"
    container_name: "stocktakingbackend"
    ports:
      - "8081:8081"
    depends_on:
      - stock-db

volumes:
  postgres-data:
