@startuml
!includeurl https://raw.githubusercontent.com/RicardoNiepel/C4-PlantUML/release/1-0/C4_Container.puml

title Диаграмма контекста

'Person(leader, "Руководитель")
Person(office_manager, "Офис-менеджер")
Person(supply_manager, "Завхоз")
Person(project_manager_in_the_company, "Менеджер проекта в компании")

System(Stocktaking, "Stocktaking")

'Rel(leader, Stocktaking, "Руководит")
Rel(office_manager, Stocktaking, "Ставит на баланс предметы, печатает qr коды")
Rel(supply_manager, Stocktaking, "Проверка наличия предмета, определение ответственного за предмет")
Rel(project_manager_in_the_company, Stocktaking, "Оборудование рабочего места для нового разработчика")

@enduml