linters:
  enable-all: true
  disable:
    - lll
    - gochecknoglobals
    - prealloc
    - gosec

linters-settings:
  govet:
    # report about shadowed variables
    check-shadowing: true
  goimports:
    local-prefixes: "stocktakingbackend"
  gocritic:
    enabled-tags:
      - experimental
      - opinionated
