apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    io.kompose.service: stocktakingweb
  name: stocktakingweb
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    spec:
      containers:
      - env:
        - name: STOCK_DOMAIN
          value: localhost
        image: psshpak/stocktakingweb
        name: stocktakingweb
        ports:
        - containerPort: 80
        - containerPort: 443
        resources: {}
        volumeMounts:
        - mountPath: /etc/ssl/extra
          name: stocktakingweb-claim0
      restartPolicy: Always
      volumes:
      - name: stocktakingweb-claim0
        persistentVolumeClaim:
          claimName: stocktakingweb-claim0
status: {}
